version: '3'

services:
  nextjs:
    build: .
    ports:
      - "3000:80"
    volumes:
      - ./public:/usr/share/nginx/html
    restart: always

  nginx:
    build:
      context: .
      dockerfile: nginx.dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./private.key:/etc/nginx/private.key
      - ./bundle.crt:/etc/nginx/bundle.crt
    depends_on:
      - nextjs
    restart: always
