export const DOCUMENT_TITLE = 'Kỳ Anh Nguyễn | Photographer'
export const APP_VERSION = '0.0.1'
export const APP_NAME = 'app'
export const DEFAULT_GMT = '+07:00'
export const DEFAULT_PHONE_COUNTRY_CODE = '+84'
